version: "3"

services:

  app:
    build: 
      context: node
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./node/mysql:/docker-entrypoint-initdb.d
    environment: 
    - MYSQL_DATABASE=nodedb
    - MYSQL_ROOT_PASSWORD=root
    networks: 
    - node-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports: 
      - "8080:80"
    depends_on:
      - app

networks: 
  node-network:
    driver: bridge